name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint & Typecheck
        run: npm run build --if-present

      - name: Run Unit Tests
        run: npm test

      - name: Start Next.js
        run: npm start &

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/**/*.cy.js
          browser: chrome
          headless: true
          start: npm start 