name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint & Typecheck
        run: npm run build --if-present

      - name: Run Unit Tests
        run: npm test

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          spec: cypress/e2e/**/*.cy.js
          browser: chrome
        env:
          # Pass the secret to Cypress environment
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          # Pass other necessary env vars if Cypress tests need them
          # Example: GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }} # Add if needed
          # Example: DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }} # Add if needed 